# Generated by Django 3.1.4 on 2020-12-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201217_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(choices=[('< 5.4', '< 5.4'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'), ('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'), ('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d'), ('5.13a', '5.13a'), ('5.13b', '5.13b'), ('5.13c', '5.13c'), ('5.13d', '5.13d')], max_length=10),
        ),
        migrations.CreateModel(
            name='Sends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('T', 'Traditional'), ('SP', 'Sport'), ('TR', 'Top Rope'), ('S', 'Free Solo'), ('A', 'Aid Climbed'), ('B', 'Boulder')], default='T', max_length=10)),
                ('info', models.CharField(choices=[('RP', 'Redpoint'), ('PP', 'Pinkpoint'), ('OS', 'Onsight'), ('F', 'Flash')], default='RP', max_length=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.route')),
            ],
        ),
    ]
