# Generated by Django 3.1.4 on 2020-12-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201221_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sends',
            new_name='Send',
        ),
    ]
