# Generated by Django 3.1.4 on 2020-12-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_climber_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climber',
            name='routes',
        ),
        migrations.AddField(
            model_name='route',
            name='climbers',
            field=models.ManyToManyField(to='main_app.Climber'),
        ),
    ]
